version: "3.8"

services:
  backend-users-node:
    container_name: backend-users-node
    build:
      context: ./backend-users-node
    ports:
      - "5000:5000"
    environment:
      - KAFKA_HOST=kafka:9092
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=library
      - JWT_SECRET=adib1234
      - SPRING_BOOT_BASE_URL=http://library-management-backend:8080/api
    depends_on:
      - db
      - kafka
    networks:
      - library-net

  library-management-backend:
    container_name: library-management-backend
    build:
      context: ./library-management-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_APPLICATION_NAME=library-management-backend
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/library
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
    depends_on:
      - db
    networks:
      - library-net

  kafka:
    image: wurstmeister/kafka:latest
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_LISTENER_NAME_INTERNAL: INSIDE
      KAFKA_LISTENER_INTERNAL_PORT: 9093
      KAFKA_LISTENER_EXTERNAL: OUTSIDE
      KAFKA_LISTENER_EXTERNAL_PORT: 9092
      KAFKA_LISTENER_MODE: "global"
      KAFKA_LISTENER_NAME_OUTSIDE: OUTSIDE
      KAFKA_LISTENER_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    expose:
      - "9092"
    networks:
      - library-net

  zookeeper:
    image: wurstmeister/zookeeper:latest
    expose:
      - "2181"
    networks:
      - library-net

  db:
    image: mysql:8
    container_name: library-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: library
    ports:
      - "3306:3306"
    networks:
      - library-net

  library-frontend:
    build:
      context: ./library-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_USER_SERVER_URI=http://backend-users-node:5000
      - NEXT_PUBLIC_JWT_SECRET=adib1234
    networks:
      - library-net

  user-frontend:
    build:
      context: ./user-frontend
    ports:
      - "4000:3000"
    environment:
      - NEXT_PUBLIC_USER_SERVER_URI=http://backend-users-node:5000
      - NEXT_PUBLIC_JWT_SECRET=adib1234
    networks:
      - library-net

networks:
  library-net:
    driver: bridge